### ISSUE TITLE
Elmerfem installs its own copy of ARPACK

### ISSUE THREAD

**Issue by Schamschula** [ElmerCSC/elmerfem#120]
I've been trying to install ElmerFEM under MacPorts. I have no problem building the package (I haven't tried all optional variants), but I have a failure when activating:

elmerfem tries to install /opt/local/lib/libarpack.dylib

which conflicts with the MacPorts arpack package, which has numerous dependent package in my case.

Unfortunately, cmake is not set up to test for arpack and add the correct path/library to the link settings.

In `src/mathlibs/CMakeLists.txt` there only is `ADD_SUBDIRECTORY(arpack)`which then builds the local version of arpack.

**Comment by raback** [comment]
ARPAKC has been a part of Elmer for a long time and I think the API has been tailored for Elmer needs. Also some bugs have been fixed (probably these have been fixed in the main branch as well). Therefore it could be a larger project to take use of the external ARPACK. Do you need the eigenmode solver? It would probably be easier to make Elmer skip the local arpack routines.

**Comment by juhanikataja** [comment]
ARPACK should get installed under `lib/elmersolver/` instead of just `lib/`.

**Comment by mmuetzel** [comment]
It looks like it is installing `libarpack.dylib` to `lib/elmersolver/` now:
https://github.com/ElmerCSC/elmerfem/actions/runs/10283579126/job/28458520635#step:7:276
```
-- Installing: /Users/runner/work/elmerfem/elmerfem/usr/lib/elmersolver/libarpack.dylib
-- Installing: /Users/runner/work/elmerfem/elmerfem/usr/lib/elmersolver/libparpack.dylib
```

This issue can probably be closed.
