### ISSUE TITLE
Up-to-date information about contributions

### ISSUE THREAD

**Issue by kinnala** [ElmerCSC/elmerfem#242]
I cannot find up-to-date information from the repository about how to contribute to Elmer. In particular,
- Is a transfer of copyright required in order to contribute or is it enough to start bombarding you with PR's?
- If yes, does it apply to all sublibraries?
- Are you able to add this information to README so that it can be easily found?

The current version of README reads as if any pull requests are welcome, which makes me believe that no transfer of copyright is required. However, from the forums I found this quote, dated 2013:
> As a small complication to be able to freely commit to the Elmer library the developer must sign a Contributor Agreement (CA) that grants IP rights also to CSC. This way we can make changes in the licensing, if that would be needed in the future.

**Comment by raback** [comment]
There may be conflicting pieces of information. We should indeed check it. The contributor agreement relates to contributions to ElmerSolver library and even there it is rather relaxed Apache type of agreement. We might want to make the code more free some day, who knows. Like we did last time when the library was relaxed from GPL to LGPL. The individual solver modules can be more relaxed because they are dynamically loaded. Hence we could have different types of modules linked with the library part. For example, Elmer/Ice community has tens of specialized modules and we don't try to control that IP wise at all.

**Comment by kinnala** [comment]
I'm attempting to write this in a concise form and propose it to be included in the README. I'll do it in order to allow potential future contributors to evaluate their chances of participating to the project. However, I'm not yet sure what is exactly meant by "ElmerSolver library" so I'll ask a clarification. Sorry for being such a nitpick.

My current impression is that "ElmerSolver library" is the source code in `fem/` excluding the source code in `fem/modules/`. Is this correct or are also nontrivial contributions to `fem/modules/*` subject to the Contributor Agreement? How about contributions to `fhutiter/` and `matc/`?

**Comment by raback** [comment]
I added the CLA's and some policy test under:
https://github.com/ElmerCSC/elmerfem/tree/devel/license_texts

fem/src/*.F90, matc, fhutiter are under LGPL (libraries). Rest is under GPL.
