### ISSUE TITLE
Stranded homogenization coefficients not printed to dat.names

### ISSUE THREAD

**Issue by jvencels** [ElmerCSC/elmerfem#361]
When running test case mgdyn2D_scan_homogenization_elementary_solutions,
not getting the following coefficients:

  74: res: nu_11_component(5) re
  75: res: nu_11_component(5) im
 139: res: nu_22_component(5) re
 140: res: nu_22_component(5) im
 141: res: sigma_33_component(5) re
 142: res: sigma_33_component(5) im

For comparison, original dat.names file can be used for comparison
fem/tests/mgdyn2D_scan_homogenization_elementary_solutions/6801/dat/6801.dat.names

**Comment by ettaka** [comment]
FYI @raback @juharu

I think the "Additive Namespaces" feature does not work properly.

In https://github.com/ElmerCSC/elmerfem/blob/devel/fem/tests/mgdyn2D_scan_homogenization_elementary_solutions/sif/6801.sif#L29

We have set
`Additive Namespaces = Logical True`

And in
https://github.com/ElmerCSC/elmerfem/blob/devel/fem/tests/mgdyn2D_scan_homogenization_elementary_solutions/sif/6801.sif#L221

we set in component a keyword with a namespace as

`Coupled 1: Homogenization Reluctivity Output Component = String 11`

However, when we try to fetch the keyword in:
https://github.com/ElmerCSC/elmerfem/blob/devel/fem/src/modules/MagnetoDynamics2D.F90#L3879
It is not found.

Just to confirm that the keyword is found when "Coupled 1:" is removed in front of the keyword, like this:
`Homogenization Reluctivity Output Component = String 11`

However, note that this case is not working if the additive namespaces are broken.

The affore mentioned keywords
```
74: res: nu_11_component(5) re
75: res: nu_11_component(5) im
139: res: nu_22_component(5) re
140: res: nu_22_component(5) im
141: res: sigma_33_component(5) re
142: res: sigma_33_component(5) im
```
are thus missing because of this.

**Comment by ettaka** [comment]
On another note, we should probably add test criteria for the `nu` and `sigma` values, instead of just checking the norms. Is this possible @juharu @raback ?

**Comment by raback** [comment]
Reference Values(n) = Real s1 s2 ... sn

(works for SaveScalars and some other since yesterday)

**Comment by ettaka** [comment]
> Reference Values(n) = Real s1 s2 ... sn
> 
> (works for SaveScalars and some other since yesterday)

Thanks! This will be useful for catching errors in dataoutput! Very usefull!
I will add that to this case when the "Additive Namespaces" -feature is working again.

**Comment by jvencels** [comment]
In practice, one can run 3 separate simulations (1 iteration per steady-state) without Namespaces, but it would be great if a fix could be found.

**Comment by raback** [comment]
I tried to look at the namespace issue. I also tried to speed it up. That didn't really much improve but I revisited the logic throughout. Maybe you can check if that helps in branch "NamespaceDev".

**Comment by jvencels** [comment]
It helps. The results seem ok and equivalent to those obtained in the original test case.

I get working namespaces with devel, @raback is it already merged?

**Comment by raback** [comment]
No, this is not merged. So you mean that you get correct results with both branches?

**Comment by jvencels** [comment]
Yes. I repeated mgdyn2D_scan_homogenization_elementary_solutions with devel, and it works. Closing the issue?
