### ISSUE TITLE
Declaring boundary as a body leads to an error

### ISSUE THREAD

**Issue by ettaka** [ElmerCSC/elmerfem#363]
@raback @juharu

I am planning to implement the driving of impedance boundaries with circuits. I need to declare the driven surface as a body but I am running into an error, see: https://github.com/ElmerCSC/elmerfem/commit/3d392d0e7eb51cf9df38247551c2f6170db3f4bd

```
ERROR:: CreateDGPerm: Either all or none of DGIndexes should preexist!
STOP 1
```
Let me know what you think. Thanks!

**Comment by juharu** [comment]
! Make boundary elements to inherit the bulk indexes 
! We neglect this as for now since it seems this causes problems in deallocation later on... 
#if 0 

... 

Activating the above block in "MainUtils::CreateDGPerm()" seems to solve this problem with no adverse effects, at least 
not in this case. Might of course break some other cases ? 

Br, J

**Comment by juharu** [comment]
>Might of course break some other cases ? 
Well, at least the test "TEAM30a_3ph_transient" breaks with: 
*** Error in `ElmerSolver': free(): invalid pointer: 0x0000000002133240 *** 

in "MeshUtils::ReleaseMesh()"

**Comment by juharu** [comment]
This also fixes the TEAM30 -case: 

diff --git a/fem/src/MainUtils.F90 b/fem/src/MainUtils.F90 
index 920bd4c..fa28766 100644 
--- a/fem/src/MainUtils.F90 
+++ b/fem/src/MainUtils.F90 
@@ -731,7 +731,7 @@ CONTAINS 

! Make boundary elements to inherit the bulk indexes 
! We neglect this as for now since it seems this causes problems in deallocation later on... 
-#if 0 
+#if 1 
DO t=Mesh % NumberOfBulkElements + 1, & 
Mesh % NumberOfBulkElements + Mesh % NumberOfBoundaryElements 
Element => Mesh % Elements(t) 
@@ -773,7 +773,7 @@ CONTAINS 
DGPerm = 0 

! If we consider boundary element above do that also here 
- DO t=1,Mesh % NumberOfBulkElements !+ Mesh % NumberOFBoundaryElements 
+ DO t=1,Mesh % NumberOfBulkElements + Mesh % NumberOFBoundaryElements 
Element => Mesh % Elements(t) 

IF( Element % PartIndex == ParEnv % myPE ) THEN 
diff --git a/fem/src/MeshUtils.F90 b/fem/src/MeshUtils.F90 
index 3317cac..a0ce2be 100644 
--- a/fem/src/MeshUtils.F90 
+++ b/fem/src/MeshUtils.F90 
@@ -5080,6 +5080,7 @@ CONTAINS 
n = Element % TYPE % NumberOfNodes 
PMesh % MaxElementNodes = MAX( PMesh % MaxElementNodes, n ) 
PMesh % Elements(ind) = Element 
+ PMesh % Elements(ind) % DGIndexes => Null() 

IF( TagNormalFlip ) THEN 
PMesh % PeriodicFlip(ind) = Turn 



Anyway: 

PMesh % Elements(ind) = Element 

... that might be calling for trouble also otherwise ...

**Comment by ettaka** [comment]
> 

Thanks! If I activate the block, then it no longer complains.
I didn't try your second fix. I tried to add the patch but it was not compatible for some reason

```
patching file MainUtils.F90
patch: **** malformed patch at line 6: ! Make boundary elements to inherit the bulk indexes
```

Maybe we can deal with this later as soon as I get the circuit driving done.

Thanks!

**Comment by juharu** [comment]
I commited the changes to 'devel'. This should not break anything - at least all tests pass...

**Comment by ettaka** [comment]
FYI @juharu 

I compiled with this fix f3a70200970600dbd4786deadaf2cc6e21450275

But it seems that it does not fix the issue. Can you confirm that the commit includes all the fixes you intended?

**Comment by juharu** [comment]
Yes, I forgot one file - added it later yesterday, should be ok ?
2.12.2022 21.58 ettaka kirjoitti:


FYI @juharu 

I compiled with this fix f3a70200970600dbd4786deadaf2cc6e21450275

But it seems that it does not fix the issue. Can you confirm that the commit includes all the fixes you intended?

**Comment by ettaka** [comment]
> Yes, I forgot one file - added it later yesterday, should be ok ? 2.12.2022 21.58 ettaka kirjoitti: FYI @juharu I compiled with this fix [f3a7020](https://github.com/ElmerCSC/elmerfem/commit/f3a70200970600dbd4786deadaf2cc6e21450275) But it seems that it does not fix the issue. Can you confirm that the commit includes all the fixes you intended?
> […](#)
> -- Reply to this email directly or view it on GitHub: [#363 (comment)](https://github.com/ElmerCSC/elmerfem/issues/363#issuecomment-1335768114) You are receiving this because you were mentioned. Message ID: ***@***.***>

Hi @juharu,

Seems that it still does not work.

/Eelis

**Comment by ettaka** [comment]
@juharu 

I am wondering why defining the surface as body changes the norm in
fem/tests/mgdyn_harmonic_wire_impedanceBC/IBC.sif

**Comment by ettaka** [comment]
I pushed another case (I confirm that in fem/tests/mgdyn_harmonic_wire_impedanceBC/IBC.sif the issue is fixed):
https://github.com/ElmerCSC/elmerfem/blob/impedance_boundary_body/fem/tests/mgdyn_harmonic_wire_impedanceBC_circuit/IBC_circuit.sif

It again has the original issue:
```
ERROR:: CreateDGPerm: Either all or none of DGIndexes should preexist!
STOP 1
```
Please advise @juharu

**Comment by juharu** [comment]
Ok. I'll have a look.
7.12.2022 22.22 ettaka kirjoitti:


I pushed another case:
https://github.com/ElmerCSC/elmerfem/blob/impedance_boundary_body/fem/tests/mgdyn_harmonic_wire_impedanceBC_circuit/IBC_circuit.sif

It again has the original issue:
```
ERROR:: CreateDGPerm: Either all or none of DGIndexes should preexist!
STOP 1
```
Please advise @juharu

**Comment by juharu** [comment]
small change in "impedance_boundary_body"-branch....

**Comment by ettaka** [comment]
Thank you @juharu ! 

I have encountered another issue with the "Body Id" definition.
See https://github.com/ElmerCSC/elmerfem/commit/74be37d756d042e8fa3ccc77a029696cf84b5385

So for some reason I only get elements for which `GetBody(Element) .eq. 0` even though it should be `GetBody(Element) .eq. 3` (for the particular case mentioned in the link).

Please advice.

**Comment by juharu** [comment]
I think the trouble is that, instead of the boundary element, your routine gets pointer
to the corresponding face element. The 'body' field of the element type is not copied from
the boundary elements to the faces. I don't quite recall all the reasons why the edge
element solver does this, but surely there are some (?). Anyway you could add the
original boundary element to the argument list of your routine and check the "body"
using that ?

**Comment by ettaka** [comment]
Thanks @juharu.

I am now trying a slightly different method: associating a boundary with a component. Analogous to what we do with components. Does it make sense to you?

Anyway, I am facing an issue: https://github.com/ElmerCSC/elmerfem/commit/fc1974735c00bf9806c7bcb17807662e35d37c14

Could you help? Thanks!
