### ISSUE TITLE
Refer to Materials by Name instead of number

### ISSUE THREAD

**Issue by nikosavola** [ElmerCSC/elmerfem#409]
I wonder would it be possible to refer to Materials for Bodies by name instead of number? So that the following would work:
```
Material 1
  Name = "Vacuum"
  Relative Permittivity = 1.0
End

Body 1
  Target Bodies(1) = $ vacuum
  Equation = 1
  Material = "Vacuum"
End
```

Instead of having `Material = 1`.

**Comment by ettaka** [comment]
@nikosavola If you want to do it for better readability, you can always define `$ vacuum_material = 1` in `Material 1` and then use `Material = $ vacuum_material` in `Body 1`. If there is some other reason, let me know and let's try to make it work.

**Comment by ettaka** [comment]
One option to implement what you want is to create a subroutine that adds a `Material = 1` (there is a subroutine for adding a keyword to a section) based on some other keyword, say, `Material Name = "Vacuum"`. The subroutine would then have to be called before the model creation. The reason the same keyword cannot be used is because keywords are strongly typed. Normally you would actually have to put `Material = Integer 1`, but you can leave it out because SOLVER.KEYWORDS defines the known keyword types.

**Comment by nikosavola** [comment]
> @nikosavola If you want to do it for better readability, you can always define `$ vacuum_material = 1` in `Material 1` and then use `Material = $ vacuum_material` in `Body 1`. If there is some other reason, let me know and let's try to make it work.

I think this method works fine, I'll close the issue. Thanks!
