### ISSUE TITLE
Error: Symbol ‘freenames’ at (1) has no IMPLICIT type; did you mean ‘filename’?

### ISSUE THREAD

**Issue by UnlimitedR** [ElmerCSC/elmerfem#497]
Error message when I'm trying to build this project
```bash
[ 54%] Building Fortran object fem/src/CMakeFiles/elmersolver.dir/ModelDescription.F90.o
/root/Projects/elmerfem/fem/src/ModelDescription.F90:359:31:

  359 |            CheckAbort,FreeNames,'simulation' )
      |                               1
Error: Symbol ‘freenames’ at (1) has no IMPLICIT type; did you mean ‘filename’?
gmake[2]: *** [fem/src/CMakeFiles/elmersolver.dir/build.make:244: fem/src/CMakeFiles/elmersolver.dir/ModelDescription.F90.o] Error 1
gmake[1]: *** [CMakeFiles/Makefile2:17525: fem/src/CMakeFiles/elmersolver.dir/all] Error 2
gmake: *** [Makefile:166: all] Error 2
```
I found this issue was caused because line 327 of the file `ModelDescription.F90` was modified to `LOGICAL :: FValueList_treeNames=.FALSE., Echo = .FALSE., Numbering = .TRUE.` instead of `FreeNames=.FALSE.`.
However, I could not track what has introduced this modification, I used `git pull` to pull the latest code base and no warnings are given. I think I have used `git checkout` several times to fix issues while building this project (I have limited knowledge of `git`).

**Comment by raback** [comment]
I wonder in which branch you find this? At least in devel branch the whole codebase does not have any string including "treeNames".

**Comment by mmuetzel** [comment]
IIUC, that was only an issue in your local checkout and it disappeared after you reverted local changes?

In that case, I'm guessing you accidentally pasted `ValueList_t` while that file was open in an editor and your cursor was between the `F` and the `r` of `Freenames` in that line.

If you'd like to make sure that you have no local changes in any files of your Git checkout, you could restore the original versions of these files with `git restore`. If you committed changes that you'd like to no longer have in your local repository, you could run `git reset --hard HEAD~1` (or whatever number of commits you'd like to revert).

In any case, since this was only ever an issue in your local checkout (iiuc), I guess this can be closed.
