### ISSUE TITLE
Economical CI-rules for testing

### ISSUE THREAD

**Issue by raback** [ElmerCSC/elmerfem#517]
We have really nice automated actions now defined on GitHub - mainly thanx to @mmuetzel. Each test takes about ~100 min and the free monthly budget is 2000 min. So we would run quickly those resources. Perhaps we could make the rules a little more economical such that in average ~20 tests could be performed.  

My suggestion would be to limit automated testing on push to devel and release "branches". Features branches may always be launched manually. There is also the "paths" that could be used to check whether actual code has been affected but maybe this is somewhat errorprone. So my suggestions would be:

on:
  push:
    branches:
      - 'devel'
      - 'release'

Additionally, we could use [skip ci] as a commit text to skip the automated testing. We often know changes do not affect the coding, for example when adding instructions, see:
https://docs.github.com/en/actions/managing-workflow-runs-and-deployments/managing-workflow-runs/skipping-workflow-runs

Any thoughts?

**Comment by mmuetzel** [comment]
Afaict, public repositories don't have a limit on minutes:
https://docs.github.com/en/billing/managing-billing-for-github-actions/about-billing-for-github-actions
> GitHub Actions usage is free for standard GitHub-hosted runners in public repositories, and for self-hosted runners.

**Comment by mmuetzel** [comment]
> branches:
> - 'devel'
> - 'release'

I really like to be able to check the CI on any branch on my fork before opening a PR here. So, I'd prefer if the CI wouldn't be limited to run only on these two branches.

**Comment by raback** [comment]
Ok! Good to know! But maybe it is a good idea to use the [skip ci] if one knows for sure that it is not affecting the compilation / running. Given that its free the other changes don't make sense.

**Comment by mmuetzel** [comment]
I agree. Even if minutes are free, it might make sense to skip running the CI in some cases (e.g., to conserve energy).
On the other hand, having the CI run the test suite is probably more efficient than running it locally. The CI runners are probably quite energy efficient (due to being highly virtualized, scaled and distributed). Additionally, results from a CI run are accessible by anyone with a GitHub account. That might conserve energy by not needing to run the tests by multiple developers on their local machines.

And the main point of having CI: It might catch unexpected side effects of any change early on (ideally even before they are merged to the main branch).
