### ISSUE TITLE
Results Out Put

### ISSUE THREAD

**Issue by mrkearden** [ElmerCSC/elmerfem#601]
Whatever the fix was for the gmsh 5 days ago broke my results output to vtu, everytime ElmerSOlver gets to results output it crashes

WritePostFile: Saving results in ElmerPost format to file case1
At line 5311 of file /build/elmerfem-csc-eg-cTdPL6/elmerfem-csc-eg-9.0/fem/src/ModelDescription.F90 (unit = 29)
Fortran runtime error: Cannot open file 'res/case1': No such file or directory

Error termination. Backtrace:
#0  0x7fac284eed11 in ???
#1  0x7fac284ef859 in ???
#2  0x7fac284f053f in ???
#3  0x7fac2872f9c6 in ???
#4  0x7fac2872fcbc in ???
#5  0x7fac2891718d in __modeldescription_MOD_writepostfile
	at /build/elmerfem-csc-eg-cTdPL6/elmerfem-csc-eg-9.0/fem/src/ModelDescription.F90:5311
#6  0x7fac28d67bc6 in savetopost
	at /build/elmerfem-csc-eg-cTdPL6/elmerfem-csc-eg-9.0/fem/src/ElmerSolver.F90:3879
#7  0x7fac28d6efba in execsimulation
	at /build/elmerfem-csc-eg-cTdPL6/elmerfem-csc-eg-9.0/fem/src/ElmerSolver.F90:3312
#8  0x7fac28d76148 in elmersolver_
	at /build/elmerfem-csc-eg-cTdPL6/elmerfem-csc-eg-9.0/fem/src/ElmerSolver.F90:672
#9  0x559efd8d53f5 in solver
	at /build/elmerfem-csc-eg-cTdPL6/elmerfem-csc-eg-9.0/fem/src/Solver.F90:57
#10  0x559efd8d515e in main
	at /build/elmerfem-csc-eg-cTdPL6/elmerfem-csc-eg-9.0/fem/src/Solver.F90:34

**Comment by raback** [comment]
This is fairly strange. I did check the places involved here and these where not really touched. ElmerSolver.F90 and ResultOutputSolver.F90 had no functional change. What changed is that GmshOutput moved from being a DLL to being part of library so that it can be called internally for adaptivity. I don't get it why the code would go now to saving in the ElmerPost format. 

Sometimes you need to compile from scratch and not just update. I guess you're compiling yourself? There are multiple platforms being tested and they seem to be fine.

**Comment by mrkearden** [comment]
I am compiling myself. I went back to a commit on 10/19 and that compiled
and ran fine

**Comment by mrkearden** [comment]
I will try it from scratch

**Comment by mrkearden** [comment]
Compiling from scratch did not work

**Comment by mrkearden** [comment]
I tried the full build from scratch again and it worked.
